function code_text_out = stripLabConversionCode(code_text_in)
    % In the input code fragment, generated by the Image Segmenter app,
    % strip out the line that includes the rgb2lab() call, as well as the
    % corresponding code comment.

    % Convert the input code text to a string array, one string element per
    % line.
    lines = split(string(code_text_in),newline);

    % Strip out the line containing the call to rgb2lab().
    lines(contains(lines,"rgb2lab(RGB)")) = [];

    % Strip out the associated comment, using the localized text.
    lines(contains(lines,...
        getString(message('images:imageSegmenter:convertLabComment')))) = [];

    % Return code text as a single string or a char vector, depending on
    % the form of the input text.
    code_text_out = join(lines,newline);
    if ischar(code_text_in)
        code_text_out = char(code_text_out);
    end
end

% Copyright 2022 The MathWorks, Inc.