function initVictoryScreen(obj)
    % 計算中央位置
    centerX = obj.ScreenWidth / 2;
    centerY = obj.ScreenHeight / 2;
    
    vicLbl=uilabel(obj.VictoryPanel);
    vicLbl.Text = 'victory!!!';
    vicLbl.FontSize = 48;
    vicLbl.FontColor = 'w';
    vicLbl.Position = [centerX-100 centerY+150 200 100];
    vicLbl.HorizontalAlignment = 'center'; % maybe unnecessary

    % 按鈕基礎樣式
    btnStyle = {
        'FontSize', 24,...
        'BackgroundColor', [0.2 0.6 1],... % 主畫面按鈕藍色
        'FontColor', 'w'};
    
    % 選擇關卡按鈕
    levelBtn = uibutton(obj.VictoryPanel, 'push',...
        'Text', '選擇關卡',...
        'Position', [centerX-100 centerY 200 60],...
        'ButtonPushedFcn', @(src,event) obj.switchPanel('level'),...
        btnStyle{:});
    
    % 返回主畫面按鈕
    mainBtn = uibutton(obj.VictoryPanel, 'push',...
        'Text', '主畫面',...
        'Position', [centerX-100 centerY-100 200 60],...
        'ButtonPushedFcn', @(src,event) obj.switchPanel('main'),...
        btnStyle{:});
    
    % 退出遊戲按鈕(紅色突出)
    quitBtn = uibutton(obj.VictoryPanel, 'push',...
        'Text', '退出遊戲',...
        'Position', [centerX-100 centerY-200 200 60],...
        'ButtonPushedFcn', @(src,event) obj.quitGame(),...
        'FontSize', 24,...
        'FontColor', 'w',...
        'BackgroundColor', [0.8 0.2 0.2]); % 紅色
end
