function initPlayer(obj)
    % 玩家角色初始化
    obj.Player = struct(...
        'Position', [400 50],...
        'Size', 30,...
        'Health', 1314,...
        'Attack', 520,...
        'Graphic', []);
    
    % 創建玩家圖形
    obj.Player.Graphic = rectangle(obj.GameAxes, 'Position',[0 0 30 30],...
        'FaceColor','b');
    
    % 更新位置
    updatePosition(obj.Player.Graphic, obj.Player.Position);
end