% 初始化暫停選單（新增）
function initPauseMenu(obj)
    % 半透明背景面板已在構造函數中建立
    
    % 暫停選單容器
    menuContainer = uipanel(obj.PausePanel,...
        'Position', [(obj.gameWidth-300)/2 (obj.gameHeight-300)/2 300 300],...
        'BackgroundColor', [0.3 0.3 0.3]);
    
    % 暫停標籤
    uilabel(menuContainer,...
        'Text', '遊戲已暫停',...
        'Position', [50 250 200 40],...
        'FontSize', 24,...
        'FontColor', 'w',...
        'HorizontalAlignment', 'center');
    
    % 按鈕樣式
    btnStyle = {'FontSize', 18, 'FontColor', 'w', 'FontWeight', 'bold'};
    
    % 繼續按鈕
    resumeBtn = uibutton(menuContainer, 'push',...
        'Text', '繼續遊戲',...
        'Position', [50 200 200 60],...
        'BackgroundColor', [0.2 0.6 0.2],...
        'ButtonPushedFcn', @(src,event) obj.togglePause(),...
        btnStyle{:});
    
    % 主選單按鈕
    mainMenuBtn = uibutton(menuContainer, 'push',...
        'Text', '返回主畫面',...
        'Position', [50 110 200 60],...
        'BackgroundColor', [0.2 0.2 0.6],...
        'ButtonPushedFcn', @(src,event) obj.switchPanel('main'),...
        btnStyle{:});
    
    % 離開遊戲按鈕
    quitBtn = uibutton(menuContainer, 'push',...
        'Text', '離開遊戲',...
        'Position', [50 20 200 60],...
        'BackgroundColor', [0.6 0.2 0.2],...
        'ButtonPushedFcn', @(src,event) obj.quitGame(),...
        btnStyle{:});
end