function formats = supportedFormats()
% Returns a cell array of formats supported by readAllIPTFormats()

% Copyright 2020-2022 The MathWorks, Inc.

imf = imformats;
formats = strcat('.',[imf.ext]);

% IPT extensions
formats = [formats, ...
    {'.dcm'},...
    {'.dic'},...
    {'.ima'},...
    {'.ntf'},...
    {'.nitf'},...
    {'.dpx'},...
    {'.exr'}];

rawFormats = {'.dng', '.nef','.cr2','.crw','.arw','.raf','.kdc','.mrw','.orf','.raw','.rw2','.srw','.pef','.x3f','.DNG','.NEF','.CR2','.CRW','.ARW','.RAF','.KDC','.MRW','.ORF','.RAW','.RW2','.SRW','.PEF','.X3F'};
formats = [formats, rawFormats ];

end