function renderToolbars(this)
%

% Copyright 2017-2023 The MathWorks, Inc.

% Add the Export to ImageViewer toolbar button.
this.IVExporterButton = uipushtool( ...
    this.Application.Handles.mainToolbar, ...
    'Tag','uimgr.uipushtool_IVExporter', ...
    'BusyAction', 'cancel', ...
    'Interruptible', 'off', ...
    'Tooltip', getString(message('images:implayUIString:exportToImageViewerTooltip')), ...
    'Click', @(hco,ev) lclExport(this), ...
    'CData', this.Application.getIcon('export_to_imtool'), ...
    'Separator','on');
