classdef Badge
    %
    
    % Copyright 2020-2022 The MathWorks, Inc.
   enumeration
      
       Empty, Done, Error, Stale, Waiting, FullCheckerboard, PartialCheckerboard, ...
           Selected, Warning, LabelingRequired, LabelingInProgress,...
           ReviewRequired, ReviewInProgress, ReadyToExport, ReviewRequiredUnsent, ...
           ReadyForExportUnsent, LabelingRequiredUnsent, ...
           InUnpublishedLT, LockedByLabeler,  LabelDoneNeedRT, ...
           InUnpublishedRT, LockedByReviewer, LabelReviewDone, ...
           DoneUnsent, DoneSent, RejectedUnsent, ...
   end
   
end
