function refinedL = refineBorders(L)
% Helper function that refines the label matrix generated by SAM Automatic
% Segmentation

    % Get unique labels in input. Ignore the background.
    labels = unique(L);
    labels = labels(labels ~= 0);

    % Initialize the output
    refinedL = zeros(size(L), "like", L);

    % Create a structuring element for morphological operations
    se = strel("disk", 2);

    for cnt = 1:numel(labels)
        currLabel = labels(cnt);

        mask = L == currLabel;

        openedMask = imopen(mask, se);

        refinedL(openedMask) = currLabel;
    end
end

%   Copyright 2024, The MathWorks Inc.