function registerIPTExtensions(ext)
%REGISTERIPTEXTENSIONS Register Image Processing Toolbox scope extensions.

% Copyright 2015-2023 The MathWorks, Inc.

% Continue calling this extension "Image Tool" even though it brings up the
% Image Viewer app. Rationale is numerous downstream components refer to it
% as "Image Tool" and they cannot be changed easily. This name is an
% internal name.
r = ext.add('Tools',...
    'Image Tool',...
    'iptscopes.ImageViewerExporter', ...
    getString(message('images:imageViewer:clientExportExtDesc')),...
    getString(message('images:imageViewer:appTitle')));
r.Depends = {'Visuals:Video'};

r = ext.add('Tools',...
    'Pixel Region',...
    'iptscopes.PixelRegionTool', ...
    getString(message('images:imtool:pixelRegionExtDesc')),...
    getString(message('images:commonUIString:pixelRegion')));
r.Depends = {'Visuals:Video'};

r = ext.add('Tools',...
    'Image Navigation Tools',...
    'iptscopes.ImageNavigationTool', ...
    getString(message('images:imtool:panZoomExtDesc')),...
    getString(message('images:implayUIString:imageNavToolsLabel')));

r.Depends = {'Visuals:Video'};

r = ext.add('Visuals',...
    'Video',...
    'iptscopes.VideoVisual',...
    getString(message('images:implayUIString:TextVideoVisualization')),...
    getString(message('images:implayUIString:VideoLabel')));

% Scope specific information (DataHandlers)
uiscopes.addDataHandler(ext, 'File', 'Video', 'scopeextensions.VideoFileHandler');
uiscopes.addDataHandler(ext, 'Workspace', 'Video', 'scopeextensions.VideoWkspHandler');

% [EOF]